Feat/add fail on like cli support
snyk-tech-services/snyk-delta pull request #124
Opened 2022-06-21 14:51 UTC by aarlaud

- [x] Tests written and linted [ℹ︎](https://github.com/snyk/general/wiki/Tests)
- [ ] Documentation written [ℹ︎](https://github.com/snyk/general/wiki/Documentation)
- [x] Commit history is tidy [ℹ︎](https://github.com/snyk/general/wiki/Git)

### What this does

Adds fail-on support like Snyk cli so the return code can be non 0 only if new vulns are upgradable, or patchable, or both.
Also  unskip a test by fixing fixtures mostly.

2022-06-21 14:56 UTC, lili2311 commented on test/lib/index-module.test.ts
> +  // it('Test module mode - no new issue', async () => {
intentional?

2022-06-21 15:03 UTC, lili2311 requested changes

2022-06-21 15:38 UTC, aarlaud commented on test/lib/index-module.test.ts
> +  // it('Test module mode - no new issue', async () => {
argh !!

2022-06-21 15:38 UTC, aarlaud commented on src/lib/index.ts
> +      debug("Fail On flag can only have the following values: [all,upgradable,patchable]");
yargs already takes care of that when using it inline.

2022-06-21 15:39 UTC, aarlaud commented on src/lib/snyk/snyk_utils.ts
>  //import * as Configstore from '@snyk/configstore';
why? it's used below

2022-06-22 09:41 UTC, lili2311 commented on src/lib/snyk/snyk_utils.ts
>  //import * as Configstore from '@snyk/configstore';
To clarify, I meant to drop the commented out line
> //import * as Configstore from '@snyk/configstore';

2022-06-22 09:42 UTC, lili2311 commented on src/lib/index.ts
> +      debug("Fail On flag can only have the following values: [all,upgradable,patchable]");
I thought so too, so what does this add then?

2022-06-22 09:42 UTC, lili2311 commented on src/lib/index.ts
> +debug("failon: ",failOnFlag)
missing spaces/formatting?

2022-06-22 12:11 UTC, merged